## Create Elevator (Success)
POST http://localhost:8000/api/elevators/add/ HTTP/1.1
Content-Type: application/json

{
    "user_name": "LIFT1",
    "controller_type": "Digital",
    "machine_type": "gearless",
    "building": 1,
    "machine_number": "XYZ123",
    "capacity": 1000,
    "manufacturer": "LiftCo",
    "installation_date": "2023-01-01",
    "maintenance_company_profile": 1,
    "developer_profile": 1,
    "technician_profile": 1
}


## Create Elevator (Success)
POST http://localhost:8000/api/elevators/add/ HTTP/1.1
Content-Type: application/json

{
    "user_name": "LIFT2",
    "controller_type": "Analog",
    "machine_type": "geared",
    "building": 5,
    "machine_number": "ABC456",
    "capacity": 1500,
    "manufacturer": "ElevatorCorp",
    "installation_date": "2024-01-01",
    "maintenance_company_profile": null,
    "developer_profile": null,
    "technician_profile": null
}


PUT http://127.0.0.1:8000/api/elevators/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer your-jwt-token

{
  "user_name": "LIFT20",
  "controller_type": "NewController",
  "machine_type": "NewMachineType",
  "building": 1,
  "machine_number": "MACHINE123",
  "capacity": 1000,
  "manufacturer": "NewManufacturer",
  "installation_date": "2024-01-01",
  "maintenance_company_profile": 1,
  "developer_profile": 1,
  "technician_profile": 1
}

# PATCH: Update specific fields of an elevator (e.g., machine_number and capacity).

PATCH http://127.0.0.1:8000/api/elevators/1/ HTTP/1.1
Content-Type: application/json

{
  "machine_number": "M99999",
  "capacity": 1500
}

DELETE http://127.0.0.1:8000/api/elevators/1/ HTTP/1.1
Authorization: Bearer your-jwt-token

