# Generated by Django 5.1.3 on 2025-01-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brokeruser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='brokeruser',
            name='referral_code',
            field=models.CharField(help_text='Unique referral code for the broker.', max_length=8, unique=True),
        ),
    ]
