# Generated by Django 5.1.3 on 2025-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_alter_brokeruser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeruser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
