# Generated by Django 5.1.3 on 2025-01-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_alter_brokerreferral_maintenance_company'),
        ('maintenance_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerreferral',
            name='maintenance_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='maintenance_companies.maintenancecompanyprofile'),
        ),
    ]
