# Generated by Django 5.1.3 on 2025-01-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('brokers', '0005_alter_brokerreferral_maintenance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerreferral',
            name='maintenance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='account.maintenance'),
        ),
    ]
