# Generated by Django 5.1.3 on 2025-02-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_alter_brokerreferral_maintenance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeruser',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage earned by the broker (default is 12.5%).', max_digits=5, null=True),
        ),
    ]
