# Generated by Django 5.1.3 on 2025-01-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='account.maintenance')),
            ],
        ),
    ]
