# Generated by Django 5.1.4 on 2024-12-20 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancecompanyprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
