# Generated by Django 5.1.4 on 2024-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
