<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-20 06:43
=======
# Generated by Django 5.1.3 on 2025-01-04 17:51
>>>>>>> 599bc3919ee2d2b1d710c4b3cba10c43d769a0fb

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to='account.technician')),
            ],
        ),
    ]
