# Generated by Django 5.1.3 on 2025-01-20 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('buildings', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingLevelAdhocSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when this ad-hoc schedule is planned to occur.')),
                ('description', models.TextField(help_text='Briefly describe the purpose of this ad-hoc schedule.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='scheduled', help_text='The current status of this ad-hoc schedule.', max_length=20)),
                ('building', models.ForeignKey(help_text='The building linked to this ad-hoc schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='building_level_adhoc_schedules', to='buildings.building')),
                ('maintenance_company', models.ForeignKey(help_text='The maintenance company handling this ad-hoc schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='building_level_adhoc_schedules', to='account.maintenance')),
                ('technician', models.ForeignKey(help_text='The technician assigned to this ad-hoc schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='building_level_adhoc_schedules', to='account.technician')),
            ],
            options={
                'verbose_name': 'Building Level Adhoc Schedule',
                'verbose_name_plural': 'Building Level Adhoc Schedules',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
