# Generated by Django 5.1.3 on 2025-01-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
