# Generated by Django 5.1.3 on 2025-01-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_maintenanceschedule_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='processed',
        ),
    ]
