# Generated by Django 5.1.3 on 2025-01-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('maintenance_companies', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('upcoming', 'Upcoming Maintenance'), ('scheduled', 'Maintenance Scheduled'), ('adhoc_task', 'Ad-Hoc Task Assigned')], max_length=20)),
                ('alert_message', models.TextField()),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('adhoc_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_task_alerts', to='jobs.adhocmaintenancetask')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts_received', to='maintenance_companies.maintenancecompanyprofile')),
                ('maintenance_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedule_alerts', to='jobs.maintenanceschedule')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_received', to='technicians.technicianprofile')),
            ],
        ),
    ]
