# Generated by Django 5.1.3 on 2025-02-01 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='default_calculation_date',
            field=models.PositiveIntegerField(default=20, help_text='Default day of the month for calculating expected payments (e.g., 25th).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='default_commission',
            field=models.DecimalField(decimal_places=2, default=9.5, help_text='Default commission percentage for brokers (e.g., 12.5%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='default_commission_duration',
            field=models.PositiveIntegerField(default=12, help_text='Default duration (in months) for which brokers earn commissions (e.g., 24 months).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='default_due_date',
            field=models.PositiveIntegerField(default=3, help_text='Default day of the month for payment due dates (e.g., 5th).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='min_charge_per_elevator',
            field=models.DecimalField(decimal_places=2, default=699.0, help_text='Default minimum charge per elevator per month.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
