# Generated by Django 5.1.3 on 2025-02-05 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_companies', '0001_initial'),
        ('payments', '0004_alter_paymentsettings_default_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='broker_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional commission percentage for the broker. Can be null if no commission is applicable.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='amount_per_asset',
            field=models.DecimalField(decimal_places=2, help_text='Amount charged per elevator per month (default is Kshs. 700).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='maintenance_company',
            field=models.ForeignKey(help_text='The maintenance company associated with this payment plan.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='maintenance_companies.maintenancecompanyprofile'),
        ),
    ]
