# Generated by Django 5.1.3 on 2025-02-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('payments', '0005_paymentplan_broker_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='maintenance_company',
            field=models.ForeignKey(help_text='The maintenance company associated with this payment plan.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='account.maintenance'),
        ),
    ]
