# Generated by Django 5.1.3 on 2025-02-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('payments', '0006_alter_paymentplan_maintenance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedpayment',
            name='maintenance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_payments', to='account.maintenance'),
        ),
    ]
