# Generated by Django 5.1.3 on 2025-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_expectedpayment_maintenance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedpayment',
            name='payment_reference_code',
            field=models.CharField(blank=True, help_text='A 6-digit alphanumeric code to reference this expected payment.', max_length=6, null=True, unique=True),
        ),
    ]
