# Generated by Django 5.1.3 on 2025-02-14 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('payments', '0008_expectedpayment_payment_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='maintenance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.maintenance'),
        ),
    ]
