# Generated by Django 5.1.3 on 2025-02-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_maintenance_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-PESA receipt number after successful withdrawal.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number Receiving the money.', max_length=100, null=True),
        ),
    ]
