# Generated by Django 5.1.3 on 2025-01-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('elevators', '0002_elevatorissuelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorissuelog',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='account.developer'),
        ),
    ]
